# -*- coding: utf-8 -*-
from __future__ import unicode_literals


STATUS_DRAFT, STATUS_WAITING, STATUS_PROCESSING, STATUS_SENT, STATUS_ERROR = range(5)
STATUS_CHOICES = (
    (STATUS_DRAFT, 'Черновик'),
    (STATUS_WAITING, 'Ожидает отправки'),
    (STATUS_PROCESSING, 'Обрабатывается'),
    (STATUS_SENT, 'Отправлено'),
    (STATUS_ERROR, 'Ошибка'),
)

INFORMATION_TYPE_APPLICATION_NOTIFICATION, \
    INFORMATION_TYPE_MASS_NOTIFICATION, \
    INFORMATION_TYPE_PASSWORD_NOTIFICATION, \
    INFORMATION_TYPE_MANUAL_NOTIFICATION = range(4)
INFORMATION_TYPE_CHOICES = (
    (INFORMATION_TYPE_APPLICATION_NOTIFICATION, 'Уведомление'),
    (INFORMATION_TYPE_MASS_NOTIFICATION, 'Массовое уведомление'),
    (INFORMATION_TYPE_PASSWORD_NOTIFICATION, 'Пароль'),
    (INFORMATION_TYPE_MANUAL_NOTIFICATION, 'Ручное уведомление'),
)